---
- hosts: ceph
  sudo: True

  vars:
    proxy_env:
      http_proxy: http://proxy.tchpc.tcd.ie:8080
      https_proxy: http://proxy.tchpc.tcd.ie:8080

  tasks:
    - name: Install dependancies
      apt: name=$item state=present update-cache=yes
      with_items:
        - git
        - bzr
        - etckeeper
        - python-software-properties
      environment: "{{ proxy_env }}"

    - name: Get ceph release key
      apt_key: id=17ED316D url=https://raw.github.com/ceph/ceph/master/keys/release.asc state=present
      environment: "{{ proxy_env }}"

    - name: Add the BOBTAIL repo
      apt_repository: repo='deb http://eu.ceph.com/debian-bobtail/ $(lsb_release -sc) main' state=present
      environment: "{{ proxy_env }}"

    - name: Install CEPH
      apt: name=$item state=latest update-cache=yes
      with_items:
        - ceph
        - radosgw
      environment: "{{ proxy_env }}"
