# for use with vagrant/development
---
- hosts: ceph
  sudo: True

  vars:

  pre_tasks:
    ## install public/private keys
    - name: authorized_keys for root
      authorized_key: user=root key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" state=present

    - name: install insecure private key for root
      action: copy src=files/insecure_private_key dest=/root/.ssh/id_rsa owner=root group=root mode=0600

    - name: install insecure config for root
      action: copy src=files/insecure_config dest=/root/.ssh/config owner=root group=root mode=0600

    - name: authorized_keys for vagrant
      authorized_key: user=vagrant key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" state=present

    - name: Install dependancies
      apt: name=$item state=present update-cache=yes
      with_items:
        - python-software-properties
        - python-virtualenv
        - python-apt

    ## install ceph from upstream repos
    - name: Get ceph release key
      apt_key: id=17ED316D url=https://raw.github.com/ceph/ceph/master/keys/release.asc state=present

  roles:
    - role: common

    - role: ceph-radosgw
      mon_port: 6789
      mon_ip_a: ${ansible_default_ipv4.address}
      mon_fqdn_a: ${ansible_default_ipv4.address}
      mds_fqdn_a: ${ansible_default_ipv4.address}
      osd_fqdn_0: ${ansible_default_ipv4.address}
      osd_fqdn_1: ${ansible_default_ipv4.address}
      radosgw_hostname: ${ansible_fqdn}
      email_address: nops

  tasks:
