---
- hosts: ceph
  sudo: True

  vars:
    proxy_env:
      http_proxy: http://proxy.tchpc.tcd.ie:8080
      https_proxy: http://proxy.tchpc.tcd.ie:8080

    # Ceph
    mon_port: 6789
    mon_ip_a: ${ansible_default_ipv4.address}
    mon_fqdn_a: ${ansible_default_ipv4.address}
    mds_fqdn_a: ${ansible_default_ipv4.address}
    osd_fqdn_0: ${ansible_default_ipv4.address}
    osd_fqdn_1: ${ansible_default_ipv4.address}
    radosgw_hostname: ${ansible_fqdn}
    email_address: nops

  roles:
    - role: ceph-radosgw

  tasks:
