---
- hosts: ceph
  sudo: False

  vars:
    proxy_env:
      http_proxy: http://proxy.tchpc.tcd.ie:8080
      https_proxy: http://proxy.tchpc.tcd.ie:8080

  tasks:
    - name: install dependancies
      apt: name=$item state=present
      with_items:
        - git
        - etckeeper
      sudo: True
      environment: "{{ proxy_env }}"
