---
- hosts: radosgw-lb
  user: root

- hosts: radosgw
  user: root

  vars:

  pre_tasks:
    - name: Install dependancies
      apt: name=$item state=present update-cache=yes
      with_items:
        - python-software-properties
        - python-virtualenv
        - python-apt
      environment:
        http_proxy: http://{{proxy_server}}:{{proxy_port}}
        https_proxy: http://{{proxy_server}}:{{proxy_port}}

    ## install ceph from upstream repos
    - name: Get ceph release key
      apt_key: id=17ED316D url=https://raw.github.com/ceph/ceph/master/keys/release.asc state=present
      environment:
        https_proxy: http://{{proxy_server}}:{{proxy_port}}

  roles:
    - role: proxy
    - role: common
#
#    - role: ceph-radosgw
#      mon_port: 6789
#      mon_ip_a: ${ansible_default_ipv4.address}
#      mon_fqdn_a: ${ansible_default_ipv4.address}
#      mds_fqdn_a: ${ansible_default_ipv4.address}
#      osd_fqdn_0: ${ansible_default_ipv4.address}
#      osd_fqdn_1: ${ansible_default_ipv4.address}
#      radosgw_hostname: ${ansible_fqdn}
#      email_address: nops

  tasks:
    - apt_repository: repo='deb http://eu.ceph.com/debian-{{ceph_release}}/ $(lsb_release -sc) main' state=present

    - name: install ceph-radosgw
      apt: name=$item state=present update_cache=yes
      with_items:
        - ceph
        - radosgw
        - apache2
        - libapache2-mod-fastcgi

    # upload fragments of ceph config - base ceph config and also the fragment needed for the radosgw
    - file: path=/etc/ceph-fragment state=directory
    - template: src=templates/ceph-radosgw-fragment.conf dest=/etc/ceph-fragment/ceph-radosgw-fragment.conf
    - copy: src=private/ceph.conf dest=/etc/ceph-fragment/ceph.conf
    - assemble: src=/etc/ceph-fragment/ dest=/etc/ceph/ceph.conf backup=yes

    # create storage for the radosgw
    - name: create directories for ceph radosgw
      action: file path=$item state=directory
      with_items:
        - /var/lib/ceph/radosgw/${ansible_hostname}

    # generate key on the gateway
    #- command: ceph-authtool --create-keyring /etc/ceph/keyring.radosgw.gateway creates=/etc/ceph/keyring.radosgw.gateway
    #- command: ceph-authtool /etc/ceph/keyring.radosgw.gateway -n client.radosgw.gateway --gen-key
    # copy the key to the monitor then add it to the monitor keyring
    #- command: ceph -k /etc/ceph/ceph.keyring auth add client.radosgw.gateway -i /etc/ceph/keyring.radosgw.gateway
    - copy: src=private/keyring.radosgw.gateway dest=/etc/ceph/keyring.radosgw.gateway
    - copy: src=private/keyring.admin dest=/etc/ceph/ceph.client.admin.keyring

    # enable the services/gateway
    - name: install s3gw.fcgi script
      copy: src=files/s3gw.fcgi dest=/var/www/s3gw.fcgi mode=0555 owner=root group=root

    - name: enable some apache mods
      command: a2enmod rewrite
      notify:
        - restart apache2

    - name: enable some apache mods
      command: a2enmod fastcgi
      notify:
        - restart apache2

    - name: install default httpd.conf
      template: src=templates/httpd.conf dest=/etc/apache2/httpd.conf owner=root group=root
      notify:
      - restart apache2

    - name: install rgw.conf
      template: src=templates/rgw.conf dest=/etc/apache2/sites-available/rgw.conf owner=root group=root
      notify:
        - restart apache2

    - name: enable rgw.conf
      command: a2ensite rgw.conf
      notify:
        - restart apache2

    - name: disable default site
      command: a2dissite default
      notify:
        - restart apache2

    - name: start radosgw
      command: /etc/init.d/radosgw start

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
