---
  - name: write /etc/profile.d/proxy.sh
    action: template src=proxy.j2 dest=/etc/profile.d/proxy.sh

  - name: Configure apt to use a proxy
    action: template src=apt.j2 dest=/etc/apt/apt.conf

  - name: configure curlrc for root
    action: template src=curlrc.j2 dest=/root/.curlrc
