---
    ## boiler plate
    - name: Install dependancies
      apt: name=$item state=present update-cache=yes
      with_items:
        - git
        - bzr
        - etckeeper
        - python-software-properties
        - python-virtualenv
        - python-apt
        - curl
